name: CI

on: push

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.5.10
        env:
          EARTHLY_SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}

      - uses: actions/checkout@v3

      - name: test example app
        run: earthly -P --ci +test
